name       : doxygen
version    : 1.8.13
release    : 1
source     :
    - https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz : 11eddd68161f40a8324e41b4969da2be7df690962a8f2b1d2146159aca3e7729
license    : GPL-2.0
component  : programming.tools
summary    : The de-facto standard tool for generating documentation from annotated C++ sources
description: |
    Doxygen is the de facto standard tool for generating documentation from
    annotated C++ sources, but it also supports other popular programming
    languages such as C, Objective-C, CSharp, PHP, Java, Python, IDL (Corba,
    Microsoft, and UNO/OpenOffice flavors), Fortran, VHDL, Tcl, and to some
    extent D.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
