name       : doxygen
version    : 1.8.15
release    : 2
source     :
    - https://github.com/doxygen/doxygen/archive/Release_1_8_15.tar.gz : cc5492b3e2d1801ae823c88e0e7a38caee61a42303587e987142fe9b68a43078
license    : GPL-2.0-only
component  : programming.tools
summary    : The de-facto standard tool for generating documentation from annotated C++ sources
description: |
    Doxygen is the de facto standard tool for generating documentation from
    annotated C++ sources, but it also supports other popular programming
    languages such as C, Objective-C, CSharp, PHP, Java, Python, IDL (Corba,
    Microsoft, and UNO/OpenOffice flavors), Fortran, VHDL, Tcl, and to some
    extent D.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
