name       : doxygen
version    : 1.9.2
release    : 5
source     :
    - https://github.com/doxygen/doxygen/archive/refs/tags/Release_1_9_2.tar.gz : 40f429241027ea60f978f730229d22e971786172fdb4dc74db6406e7f6c034b3
license    : GPL-2.0-only
component  : programming.tools
summary    : The de-facto standard tool for generating documentation from annotated C++ sources
description: |
    Doxygen is the de facto standard tool for generating documentation from annotated C++ sources, but it also supports other popular programming languages such as C, Objective-C, CSharp, PHP, Java, Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors), Fortran, VHDL, Tcl, and to some extent D.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %patch -p1 < $pkgfiles/configure-manpages.patch
    %cmake_ninja -DPYTHON_EXECUTABLE=/usr/bin/python3 -Dbuild_wizard=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 solusBuildDir/man/*.1 -t $installdir/usr/share/man/man1
